import type { ThemeName } from '@/types';

interface ThemeConfig {
  titles: readonly string[];
  subtitles: readonly string[];
  categories: readonly string[];
  tags: readonly string[];
  avatarPrefix: string;
}

const ecommerce: ThemeConfig = {
  titles: [
    'Wireless Bluetooth Headphones',
    'Ergonomic Office Chair',
    'Mechanical Keyboard RGB',
    'Ultra-Wide Monitor 34"',
    'Portable SSD 1TB',
    'Smart Watch Pro',
    'Noise Cancelling Earbuds',
    'USB-C Hub Adapter',
    'Webcam 4K Ultra HD',
    'Standing Desk Converter',
    'Laptop Backpack',
    'Wireless Mouse',
    'LED Desk Lamp',
    'Cable Management Kit',
    'Monitor Light Bar',
    'Streaming Microphone',
    'Power Bank 20000mAh',
    'Phone Gimbal Stabilizer',
    'Ring Light 18"',
    'Tablet Stand Holder',
  ],
  subtitles: [
    'Premium build quality with extended warranty',
    'Best seller in its category this month',
    'New arrival — limited stock available',
    'Editor\'s choice for productivity',
    'Top rated by verified buyers',
    'Free shipping on orders over $50',
    'Bundle deal available',
    'Refurbished — like new condition',
  ],
  categories: [
    'Electronics',
    'Audio',
    'Computing',
    'Accessories',
    'Peripherals',
    'Storage',
    'Wearables',
    'Lighting',
  ],
  tags: [
    'bestseller',
    'new',
    'sale',
    'prime',
    'eco-friendly',
    'wireless',
    'usb-c',
    'portable',
    'premium',
    'budget',
  ],
  avatarPrefix: '📦',
};

const social: ThemeConfig = {
  titles: [
    'Just shipped a new feature!',
    'Anyone else struggling with CSS grid?',
    'TIL: You can use performance.now() for benchmarking',
    'Hot take: Tailwind > CSS-in-JS',
    'My side project just hit 1k stars',
    'Looking for feedback on my portfolio',
    'Finally understood React Server Components',
    'Deployed to production on a Friday AMA',
    'Best VS Code extensions for 2024?',
    'Who else loves TypeScript strict mode?',
    'Just refactored 10k lines of legacy code',
    'Is GraphQL still worth learning?',
    'My favorite terminal setup',
    'Debugging production at 3am be like...',
    'Switched from npm to pnpm — no regrets',
    'Rate my home office setup',
    'First open source contribution!',
    'Vim or Neovim in 2024?',
    'Just passed my AWS certification',
    'The state of JavaScript frameworks',
  ],
  subtitles: [
    '@devguru · 2h ago',
    '@codewitch · 5h ago',
    '@hackerman · 12h ago',
    '@pixelpusher · 1d ago',
    '@rustacean · 3h ago',
    '@fullstacker · 8h ago',
    '@cloudnative · 6h ago',
    '@opensourcer · 15m ago',
  ],
  categories: [
    'Discussion',
    'Show & Tell',
    'Question',
    'Tutorial',
    'Meme',
    'Career',
    'News',
    'Resource',
  ],
  tags: [
    'react',
    'typescript',
    'webdev',
    'javascript',
    'css',
    'node',
    'rust',
    'devops',
    'ai',
    'opensource',
  ],
  avatarPrefix: '👤',
};

const logs: ThemeConfig = {
  titles: [
    'GET /api/v1/users 200 OK',
    'POST /api/v1/auth/login 201 Created',
    'DELETE /api/v1/sessions/abc123 204',
    'GET /api/v1/products?page=2 200 OK',
    'PUT /api/v1/users/42/profile 200 OK',
    'GET /health 200 OK',
    'POST /api/v1/orders 201 Created',
    'GET /api/v1/analytics/dashboard 200 OK',
    'PATCH /api/v1/settings 200 OK',
    'GET /api/v1/search?q=react 200 OK',
    'POST /api/v1/webhooks/stripe 200 OK',
    'GET /api/v1/notifications 200 OK',
    'PUT /api/v1/cache/invalidate 204',
    'GET /api/v1/users/42/orders 200 OK',
    'POST /api/v1/uploads/image 201 Created',
    'GET /api/v1/reports/monthly 200 OK',
    'DELETE /api/v1/tokens/expired 204',
    'GET /metrics 200 OK',
    'POST /api/v1/emails/send 202 Accepted',
    'GET /api/v1/config 200 OK',
  ],
  subtitles: [
    'Response time: 12ms | Size: 2.4KB',
    'Response time: 45ms | Size: 156B',
    'Response time: 3ms | Size: 0B',
    'Response time: 89ms | Size: 12.1KB',
    'Response time: 23ms | Size: 512B',
    'Response time: 156ms | Size: 45.2KB',
    'Response time: 67ms | Size: 1.8KB',
    'Response time: 8ms | Size: 128B',
  ],
  categories: [
    'INFO',
    'DEBUG',
    'WARN',
    'ERROR',
    'TRACE',
    'HTTP',
    'DB',
    'CACHE',
  ],
  tags: [
    'api',
    'auth',
    'db-query',
    'cache-hit',
    'cache-miss',
    'slow',
    'retry',
    'timeout',
    'success',
    'error',
  ],
  avatarPrefix: '🔧',
};

const tasks: ThemeConfig = {
  titles: [
    'Fix login redirect loop on expired sessions',
    'Implement dark mode toggle',
    'Add CSV export to reports page',
    'Upgrade React to v19',
    'Refactor auth middleware for edge runtime',
    'Design mobile navigation drawer',
    'Write E2E tests for checkout flow',
    'Set up CI/CD pipeline for staging',
    'Investigate memory leak in dashboard',
    'Add rate limiting to public API',
    'Migrate database to PlanetScale',
    'Create onboarding wizard for new users',
    'Optimize image loading with blur placeholders',
    'Add Stripe webhook handler for refunds',
    'Fix timezone bug in scheduling module',
    'Implement role-based access control',
    'Add search with fuzzy matching',
    'Set up error monitoring with Sentry',
    'Build notification preferences page',
    'Audit and fix accessibility issues',
  ],
  subtitles: [
    '@sarah · High priority · Sprint 14',
    '@mike · Medium priority · Sprint 14',
    '@elena · Low priority · Backlog',
    '@jordan · Critical · Sprint 13',
    '@alex · High priority · Sprint 15',
    '@priya · Medium priority · Sprint 14',
    '@tom · Low priority · Sprint 15',
    '@lisa · High priority · Sprint 13',
  ],
  categories: [
    'Bug',
    'Feature',
    'Chore',
    'Improvement',
    'Spike',
    'Design',
    'Test',
    'Infra',
  ],
  tags: [
    'frontend',
    'backend',
    'urgent',
    'blocked',
    'in-review',
    'needs-design',
    'tech-debt',
    'dx',
    'security',
    'performance',
  ],
  avatarPrefix: '📋',
};

export const THEME_CONFIGS: Record<ThemeName, ThemeConfig> = {
  ecommerce,
  social,
  logs,
  tasks,
};
